window.KITAP_CATALOG = [
  {
    "id": "ozumuzni-etirap-qilayli",
    "title": "ئۆزىمىزنى ئېتىراپ قىلايلى",
    "author": "ئەختەم ئۆمەر",
    "price": 265,
    "priceText": "265 ₺",
    "category": "رومانلار",
    "source": "romanlar.html",
    "image": "sample-book-cover.png",
    "href": "ozumuzni-etirap-qilayli.html"
  },
  {
    "id": "romanlar-2",
    "title": "رومان كىتابى 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "رومانلار",
    "source": "romanlar.html",
    "image": "sample-book-cover.png",
    "href": "romanlar-2.html"
  },
  {
    "id": "romanlar-3",
    "title": "رومان كىتابى 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "رومانلار",
    "source": "romanlar.html",
    "image": "sample-book-cover.png",
    "href": "romanlar-3.html"
  },
  {
    "id": "romanlar-4",
    "title": "رومان كىتابى 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "رومانلار",
    "source": "romanlar.html",
    "image": "sample-book-cover.png",
    "href": "romanlar-4.html"
  },
  {
    "id": "romanlar-5",
    "title": "رومان كىتابى 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "رومانلار",
    "source": "romanlar.html",
    "image": "sample-book-cover.png",
    "href": "romanlar-5.html"
  },
  {
    "id": "romanlar-6",
    "title": "رومان كىتابى 6",
    "author": "ئاپتور ئىسمى",
    "price": 265.0,
    "priceText": "265 ₺",
    "category": "رومانلار",
    "source": "romanlar.html",
    "image": "sample-book-cover.png",
    "href": "romanlar-6.html"
  },
  {
    "id": "tarikhiy-romanlar-1",
    "title": "تارىخىي رومان 1",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "تارىخىي رومانلار",
    "source": "tarikhiy-romanlar.html",
    "image": "sample-book-cover.png",
    "href": "tarikhiy-romanlar-1.html"
  },
  {
    "id": "tarikhiy-romanlar-2",
    "title": "تارىخىي رومان 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "تارىخىي رومانلار",
    "source": "tarikhiy-romanlar.html",
    "image": "sample-book-cover.png",
    "href": "tarikhiy-romanlar-2.html"
  },
  {
    "id": "tarikhiy-romanlar-3",
    "title": "تارىخىي رومان 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "تارىخىي رومانلار",
    "source": "tarikhiy-romanlar.html",
    "image": "sample-book-cover.png",
    "href": "tarikhiy-romanlar-3.html"
  },
  {
    "id": "tarikhiy-romanlar-4",
    "title": "تارىخىي رومان 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "تارىخىي رومانلار",
    "source": "tarikhiy-romanlar.html",
    "image": "sample-book-cover.png",
    "href": "tarikhiy-romanlar-4.html"
  },
  {
    "id": "tarikhiy-romanlar-5",
    "title": "تارىخىي رومان 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "تارىخىي رومانلار",
    "source": "tarikhiy-romanlar.html",
    "image": "sample-book-cover.png",
    "href": "tarikhiy-romanlar-5.html"
  },
  {
    "id": "tarikhiy-romanlar-6",
    "title": "تارىخىي رومان 6",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "تارىخىي رومانلار",
    "source": "tarikhiy-romanlar.html",
    "image": "sample-book-cover.png",
    "href": "tarikhiy-romanlar-6.html"
  },
  {
    "id": "sheirlar-1",
    "title": "شېئىر كىتابى 1",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "شېئىرلار",
    "source": "sheirlar.html",
    "image": "images/sheir-1.jpg",
    "href": "sheirlar-1.html"
  },
  {
    "id": "sheirlar-2",
    "title": "شېئىر كىتابى 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "شېئىرلار",
    "source": "sheirlar.html",
    "image": "images/sheir-2.jpg",
    "href": "sheirlar-2.html"
  },
  {
    "id": "sheirlar-3",
    "title": "شېئىر كىتابى 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "شېئىرلار",
    "source": "sheirlar.html",
    "image": "images/sheir-3.jpg",
    "href": "sheirlar-3.html"
  },
  {
    "id": "sheirlar-4",
    "title": "شېئىر كىتابى 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "شېئىرلار",
    "source": "sheirlar.html",
    "image": "images/sheir-4.jpg",
    "href": "sheirlar-4.html"
  },
  {
    "id": "sheirlar-5",
    "title": "شېئىر كىتابى 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "شېئىرلار",
    "source": "sheirlar.html",
    "image": "images/sheir-5.jpg",
    "href": "sheirlar-5.html"
  },
  {
    "id": "sheirlar-6",
    "title": "شېئىر كىتابى 6",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "شېئىرلار",
    "source": "sheirlar.html",
    "image": "images/sheir-6.jpg",
    "href": "sheirlar-6.html"
  },
  {
    "id": "hekayiler-1",
    "title": "ھېكايە كىتابى 1",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ھېكايىلەر",
    "source": "hekayiler.html",
    "image": "images/hekaye-1.jpg",
    "href": "hekayiler-1.html"
  },
  {
    "id": "hekayiler-2",
    "title": "ھېكايە كىتابى 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ھېكايىلەر",
    "source": "hekayiler.html",
    "image": "images/hekaye-2.jpg",
    "href": "hekayiler-2.html"
  },
  {
    "id": "hekayiler-3",
    "title": "ھېكايە كىتابى 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ھېكايىلەر",
    "source": "hekayiler.html",
    "image": "images/hekaye-3.jpg",
    "href": "hekayiler-3.html"
  },
  {
    "id": "hekayiler-4",
    "title": "ھېكايە كىتابى 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ھېكايىلەر",
    "source": "hekayiler.html",
    "image": "images/hekaye-4.jpg",
    "href": "hekayiler-4.html"
  },
  {
    "id": "hekayiler-5",
    "title": "ھېكايە كىتابى 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ھېكايىلەر",
    "source": "hekayiler.html",
    "image": "images/hekaye-5.jpg",
    "href": "hekayiler-5.html"
  },
  {
    "id": "hekayiler-6",
    "title": "ھېكايە كىتابى 6",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ھېكايىلەر",
    "source": "hekayiler.html",
    "image": "images/hekaye-6.jpg",
    "href": "hekayiler-6.html"
  },
  {
    "id": "dastanlar-1",
    "title": "داستان كىتابى 1",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "داستانلار",
    "source": "dastanlar.html",
    "image": "images/dastan-1.jpg",
    "href": "dastanlar-1.html"
  },
  {
    "id": "dastanlar-2",
    "title": "داستان كىتابى 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "داستانلار",
    "source": "dastanlar.html",
    "image": "images/dastan-2.jpg",
    "href": "dastanlar-2.html"
  },
  {
    "id": "dastanlar-3",
    "title": "داستان كىتابى 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "داستانلار",
    "source": "dastanlar.html",
    "image": "images/dastan-3.jpg",
    "href": "dastanlar-3.html"
  },
  {
    "id": "dastanlar-4",
    "title": "داستان كىتابى 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "داستانلار",
    "source": "dastanlar.html",
    "image": "images/dastan-4.jpg",
    "href": "dastanlar-4.html"
  },
  {
    "id": "dastanlar-5",
    "title": "داستان كىتابى 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "داستانلار",
    "source": "dastanlar.html",
    "image": "images/dastan-5.jpg",
    "href": "dastanlar-5.html"
  },
  {
    "id": "dastanlar-6",
    "title": "داستان كىتابى 6",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "داستانلار",
    "source": "dastanlar.html",
    "image": "images/dastan-6.jpg",
    "href": "dastanlar-6.html"
  },
  {
    "id": "dunya-edebiyati-1",
    "title": "دۇنيا ئەدەبىياتى كىتابى 1",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "دۇنيا ئەدەبىياتى",
    "source": "dunya-edebiyati.html",
    "image": "images/dunya-edebiyati-1.jpg",
    "href": "dunya-edebiyati-1.html"
  },
  {
    "id": "dunya-edebiyati-2",
    "title": "دۇنيا ئەدەبىياتى كىتابى 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "دۇنيا ئەدەبىياتى",
    "source": "dunya-edebiyati.html",
    "image": "images/dunya-edebiyati-2.jpg",
    "href": "dunya-edebiyati-2.html"
  },
  {
    "id": "dunya-edebiyati-3",
    "title": "دۇنيا ئەدەبىياتى كىتابى 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "دۇنيا ئەدەبىياتى",
    "source": "dunya-edebiyati.html",
    "image": "images/dunya-edebiyati-3.jpg",
    "href": "dunya-edebiyati-3.html"
  },
  {
    "id": "dunya-edebiyati-4",
    "title": "دۇنيا ئەدەبىياتى كىتابى 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "دۇنيا ئەدەبىياتى",
    "source": "dunya-edebiyati.html",
    "image": "images/dunya-edebiyati-4.jpg",
    "href": "dunya-edebiyati-4.html"
  },
  {
    "id": "dunya-edebiyati-5",
    "title": "دۇنيا ئەدەبىياتى كىتابى 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "دۇنيا ئەدەبىياتى",
    "source": "dunya-edebiyati.html",
    "image": "images/dunya-edebiyati-5.jpg",
    "href": "dunya-edebiyati-5.html"
  },
  {
    "id": "dunya-edebiyati-6",
    "title": "دۇنيا ئەدەبىياتى كىتابى 6",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "دۇنيا ئەدەبىياتى",
    "source": "dunya-edebiyati.html",
    "image": "images/dunya-edebiyati-6.jpg",
    "href": "dunya-edebiyati-6.html"
  },
  {
    "id": "adabiyat-roman-1",
    "title": "رومان 1",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئەدەبىيات رومانلىرى",
    "source": "adabiyat-roman.html",
    "image": "images/roman-1.jpg",
    "href": "adabiyat-roman-1.html"
  },
  {
    "id": "adabiyat-roman-2",
    "title": "رومان 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئەدەبىيات رومانلىرى",
    "source": "adabiyat-roman.html",
    "image": "images/roman-2.jpg",
    "href": "adabiyat-roman-2.html"
  },
  {
    "id": "adabiyat-roman-3",
    "title": "رومان 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئەدەبىيات رومانلىرى",
    "source": "adabiyat-roman.html",
    "image": "images/roman-3.jpg",
    "href": "adabiyat-roman-3.html"
  },
  {
    "id": "adabiyat-roman-4",
    "title": "رومان 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئەدەبىيات رومانلىرى",
    "source": "adabiyat-roman.html",
    "image": "images/roman-4.jpg",
    "href": "adabiyat-roman-4.html"
  },
  {
    "id": "adabiyat-roman-5",
    "title": "رومان 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئەدەبىيات رومانلىرى",
    "source": "adabiyat-roman.html",
    "image": "images/roman-5.jpg",
    "href": "adabiyat-roman-5.html"
  },
  {
    "id": "adabiyat-roman-6",
    "title": "رومان 6",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئەدەبىيات رومانلىرى",
    "source": "adabiyat-roman.html",
    "image": "images/roman-6.jpg",
    "href": "adabiyat-roman-6.html"
  },
  {
    "id": "uyghur-adabiyati-1",
    "title": "ئۇيغۇر ئەدەبىياتى كىتابى 1",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئۇيغۇر ئەدەبىياتى",
    "source": "uyghur-adabiyati.html",
    "image": "images/uyghur-1.jpg",
    "href": "uyghur-adabiyati-1.html"
  },
  {
    "id": "uyghur-adabiyati-2",
    "title": "ئۇيغۇر ئەدەبىياتى كىتابى 2",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئۇيغۇر ئەدەبىياتى",
    "source": "uyghur-adabiyati.html",
    "image": "images/uyghur-2.jpg",
    "href": "uyghur-adabiyati-2.html"
  },
  {
    "id": "uyghur-adabiyati-3",
    "title": "ئۇيغۇر ئەدەبىياتى كىتابى 3",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئۇيغۇر ئەدەبىياتى",
    "source": "uyghur-adabiyati.html",
    "image": "images/uyghur-3.jpg",
    "href": "uyghur-adabiyati-3.html"
  },
  {
    "id": "uyghur-adabiyati-4",
    "title": "ئۇيغۇر ئەدەبىياتى كىتابى 4",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئۇيغۇر ئەدەبىياتى",
    "source": "uyghur-adabiyati.html",
    "image": "images/uyghur-4.jpg",
    "href": "uyghur-adabiyati-4.html"
  },
  {
    "id": "uyghur-adabiyati-5",
    "title": "ئۇيغۇر ئەدەبىياتى كىتابى 5",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئۇيغۇر ئەدەبىياتى",
    "source": "uyghur-adabiyati.html",
    "image": "images/uyghur-5.jpg",
    "href": "uyghur-adabiyati-5.html"
  },
  {
    "id": "uyghur-adabiyati-6",
    "title": "ئۇيغۇر ئەدەبىياتى كىتابى 6",
    "author": "ئاپتور ئىسمى",
    "price": 200.0,
    "priceText": "200 ₺",
    "category": "ئۇيغۇر ئەدەبىياتى",
    "source": "uyghur-adabiyati.html",
    "image": "images/uyghur-6.jpg",
    "href": "uyghur-adabiyati-6.html"
  },
  {
    "id": "universal-1",
    "title": "ئۇنىۋېرسال ئەسەر 1",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "ئۇنىۋېرسال",
    "source": "universal.html",
    "image": "images/universal-1.jpg",
    "href": "universal-1.html"
  },
  {
    "id": "universal-2",
    "title": "ئۇنىۋېرسال ئەسەر 2",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "ئۇنىۋېرسال",
    "source": "universal.html",
    "image": "images/universal-2.jpg",
    "href": "universal-2.html"
  },
  {
    "id": "universal-3",
    "title": "ئۇنىۋېرسال ئەسەر 3",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "ئۇنىۋېرسال",
    "source": "universal.html",
    "image": "images/universal-3.jpg",
    "href": "universal-3.html"
  },
  {
    "id": "universal-4",
    "title": "ئۇنىۋېرسال ئەسەر 4",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "ئۇنىۋېرسال",
    "source": "universal.html",
    "image": "images/universal-4.jpg",
    "href": "universal-4.html"
  },
  {
    "id": "universal-5",
    "title": "ئۇنىۋېرسال ئەسەر 5",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "ئۇنىۋېرسال",
    "source": "universal.html",
    "image": "images/universal-5.jpg",
    "href": "universal-5.html"
  },
  {
    "id": "universal-6",
    "title": "ئۇنىۋېرسال ئەسەر 6",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "ئۇنىۋېرسال",
    "source": "universal.html",
    "image": "images/universal-6.jpg",
    "href": "universal-6.html"
  },
  {
    "id": "tibb-1",
    "title": "تېبابەت ۋە ساغلاملىق 1",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "تېبابەت ۋە ساغلاملىق",
    "source": "tibb.html",
    "image": "images/tibb-1.jpg",
    "href": "tibb-1.html"
  },
  {
    "id": "tibb-2",
    "title": "تېبابەت ۋە ساغلاملىق 2",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "تېبابەت ۋە ساغلاملىق",
    "source": "tibb.html",
    "image": "images/tibb-2.jpg",
    "href": "tibb-2.html"
  },
  {
    "id": "tibb-3",
    "title": "تېبابەت ۋە ساغلاملىق 3",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "تېبابەت ۋە ساغلاملىق",
    "source": "tibb.html",
    "image": "images/tibb-3.jpg",
    "href": "tibb-3.html"
  },
  {
    "id": "tibb-4",
    "title": "تېبابەت ۋە ساغلاملىق 4",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "تېبابەت ۋە ساغلاملىق",
    "source": "tibb.html",
    "image": "images/tibb-4.jpg",
    "href": "tibb-4.html"
  },
  {
    "id": "tibb-5",
    "title": "تېبابەت ۋە ساغلاملىق 5",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "تېبابەت ۋە ساغلاملىق",
    "source": "tibb.html",
    "image": "images/tibb-5.jpg",
    "href": "tibb-5.html"
  },
  {
    "id": "tibb-6",
    "title": "تېبابەت ۋە ساغلاملىق 6",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "تېبابەت ۋە ساغلاملىق",
    "source": "tibb.html",
    "image": "images/tibb-6.jpg",
    "href": "tibb-6.html"
  },
  {
    "id": "derslik-1",
    "title": "دەرسلىك كىتاب 1",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دەرسلىك",
    "source": "derslik.html",
    "image": "images/derslik-1.jpg",
    "href": "derslik-1.html"
  },
  {
    "id": "derslik-2",
    "title": "دەرسلىك كىتاب 2",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دەرسلىك",
    "source": "derslik.html",
    "image": "images/derslik-2.jpg",
    "href": "derslik-2.html"
  },
  {
    "id": "derslik-3",
    "title": "دەرسلىك كىتاب 3",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دەرسلىك",
    "source": "derslik.html",
    "image": "images/derslik-3.jpg",
    "href": "derslik-3.html"
  },
  {
    "id": "derslik-4",
    "title": "دەرسلىك كىتاب 4",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دەرسلىك",
    "source": "derslik.html",
    "image": "images/derslik-4.jpg",
    "href": "derslik-4.html"
  },
  {
    "id": "derslik-5",
    "title": "دەرسلىك كىتاب 5",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دەرسلىك",
    "source": "derslik.html",
    "image": "images/derslik-5.jpg",
    "href": "derslik-5.html"
  },
  {
    "id": "derslik-6",
    "title": "دەرسلىك كىتاب 6",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دەرسلىك",
    "source": "derslik.html",
    "image": "images/derslik-6.jpg",
    "href": "derslik-6.html"
  },
  {
    "id": "terbiye-1",
    "title": "پەرزەنت تەربىيەسى 1",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "پەرزەنت تەربىيەسى",
    "source": "terbiye.html",
    "image": "images/terbiye-1.jpg",
    "href": "terbiye-1.html"
  },
  {
    "id": "terbiye-2",
    "title": "پەرزەنت تەربىيەسى 2",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "پەرزەنت تەربىيەسى",
    "source": "terbiye.html",
    "image": "images/terbiye-2.jpg",
    "href": "terbiye-2.html"
  },
  {
    "id": "terbiye-3",
    "title": "پەرزەنت تەربىيەسى 3",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "پەرزەنت تەربىيەسى",
    "source": "terbiye.html",
    "image": "images/terbiye-3.jpg",
    "href": "terbiye-3.html"
  },
  {
    "id": "terbiye-4",
    "title": "پەرزەنت تەربىيەسى 4",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "پەرزەنت تەربىيەسى",
    "source": "terbiye.html",
    "image": "images/terbiye-4.jpg",
    "href": "terbiye-4.html"
  },
  {
    "id": "terbiye-5",
    "title": "پەرزەنت تەربىيەسى 5",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "پەرزەنت تەربىيەسى",
    "source": "terbiye.html",
    "image": "images/terbiye-5.jpg",
    "href": "terbiye-5.html"
  },
  {
    "id": "terbiye-6",
    "title": "پەرزەنت تەربىيەسى 6",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "پەرزەنت تەربىيەسى",
    "source": "terbiye.html",
    "image": "images/terbiye-6.jpg",
    "href": "terbiye-6.html"
  },
  {
    "id": "dini-1",
    "title": "دىنىي كىتاب 1",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دىنىي كىتابلار",
    "source": "dini.html",
    "image": "images/dini-1.jpg",
    "href": "dini-1.html"
  },
  {
    "id": "dini-2",
    "title": "دىنىي كىتاب 2",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دىنىي كىتابلار",
    "source": "dini.html",
    "image": "images/dini-2.jpg",
    "href": "dini-2.html"
  },
  {
    "id": "dini-3",
    "title": "دىنىي كىتاب 3",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دىنىي كىتابلار",
    "source": "dini.html",
    "image": "images/dini-3.jpg",
    "href": "dini-3.html"
  },
  {
    "id": "dini-4",
    "title": "دىنىي كىتاب 4",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دىنىي كىتابلار",
    "source": "dini.html",
    "image": "images/dini-4.jpg",
    "href": "dini-4.html"
  },
  {
    "id": "dini-5",
    "title": "دىنىي كىتاب 5",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دىنىي كىتابلار",
    "source": "dini.html",
    "image": "images/dini-5.jpg",
    "href": "dini-5.html"
  },
  {
    "id": "dini-6",
    "title": "دىنىي كىتاب 6",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "دىنىي كىتابلار",
    "source": "dini.html",
    "image": "images/dini-6.jpg",
    "href": "dini-6.html"
  },
  {
    "id": "children-1",
    "title": "بالىلار كىتابى 1",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "بالىلار كىتابلىرى",
    "source": "children.html",
    "image": "images/balilar-1.jpg",
    "href": "children-1.html"
  },
  {
    "id": "children-2",
    "title": "بالىلار كىتابى 2",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "بالىلار كىتابلىرى",
    "source": "children.html",
    "image": "images/balilar-2.jpg",
    "href": "children-2.html"
  },
  {
    "id": "children-3",
    "title": "بالىلار كىتابى 3",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "بالىلار كىتابلىرى",
    "source": "children.html",
    "image": "images/balilar-3.jpg",
    "href": "children-3.html"
  },
  {
    "id": "children-4",
    "title": "بالىلار كىتابى 4",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "بالىلار كىتابلىرى",
    "source": "children.html",
    "image": "images/balilar-4.jpg",
    "href": "children-4.html"
  },
  {
    "id": "children-5",
    "title": "بالىلار كىتابى 5",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "بالىلار كىتابلىرى",
    "source": "children.html",
    "image": "images/balilar-5.jpg",
    "href": "children-5.html"
  },
  {
    "id": "children-6",
    "title": "بالىلار كىتابى 6",
    "author": "ئاپتور ئىسمى",
    "price": 0,
    "priceText": "0 ₺",
    "category": "بالىلار كىتابلىرى",
    "source": "children.html",
    "image": "images/balilar-6.jpg",
    "href": "children-6.html"
  }
];
