-- Kutadgu Bilig v10: analytics + scalable collection indexes
-- Safe for an existing project. No existing rows are deleted.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  book_id text,
  search_query text,
  category text,
  result_count integer,
  item_count integer,
  order_total numeric(12,2),
  path text,
  session_id text,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_name_created_idx on public.analytics_events(event_name,created_at desc);
create index if not exists analytics_events_book_created_idx on public.analytics_events(book_id,created_at desc) where book_id is not null;
create index if not exists analytics_events_search_created_idx on public.analytics_events(search_query,created_at desc) where search_query is not null;
create index if not exists books_active_new_manual_idx on public.books(is_new,created_at desc) where is_active=true;
create index if not exists books_active_recommended_manual_idx on public.books(is_recommended,created_at desc) where is_active=true;
create index if not exists books_active_sales_auto_idx on public.books(sales_count desc,created_at desc) where is_active=true;
alter table public.analytics_events enable row level security;
grant insert on public.analytics_events to anon,authenticated;
grant select on public.analytics_events to authenticated;
drop policy if exists "public can insert analytics" on public.analytics_events;
create policy "public can insert analytics" on public.analytics_events for insert to anon,authenticated with check (true);
drop policy if exists "admin can read analytics" on public.analytics_events;
create policy "admin can read analytics" on public.analytics_events for select to authenticated using (public.is_kutadgu_admin());


grant usage, select on sequence public.analytics_events_id_seq to anon,authenticated;

create or replace function public.get_kutadgu_analytics(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_since timestamptz := now() - make_interval(days => greatest(1,least(coalesce(p_days,30),365)));
  v_result jsonb;
begin
  if not public.is_kutadgu_admin() then
    raise exception 'admin only';
  end if;
  select jsonb_build_object(
    'page_views',(select count(*) from public.analytics_events where created_at>=v_since and event_name='page_view'),
    'book_views',(select count(*) from public.analytics_events where created_at>=v_since and event_name='book_view'),
    'cart_adds',(select count(*) from public.analytics_events where created_at>=v_since and event_name='add_to_cart'),
    'whatsapp_clicks',(select count(*) from public.analytics_events where created_at>=v_since and event_name='whatsapp_order_click'),
    'top_books',coalesce((
      select jsonb_agg(to_jsonb(t)) from (
        select e.book_id,coalesce(b.title,e.book_id) as title,count(*)::integer as views
        from public.analytics_events e left join public.books b on b.id=e.book_id
        where e.created_at>=v_since and e.event_name='book_view' and e.book_id is not null
        group by e.book_id,b.title order by count(*) desc limit 10
      ) t
    ),'[]'::jsonb),
    'zero_searches',coalesce((
      select jsonb_agg(to_jsonb(z)) from (
        select search_query as query,count(*)::integer as searches
        from public.analytics_events
        where created_at>=v_since and event_name='search' and coalesce(result_count,0)=0 and search_query is not null and search_query<>''
        group by search_query order by count(*) desc limit 10
      ) z
    ),'[]'::jsonb)
  ) into v_result;
  return v_result;
end $$;
grant execute on function public.get_kutadgu_analytics(integer) to authenticated;
