
(function(){
"use strict";
const C=window.KITAP_CATALOG||[];
const CART_KEY="kutadgu-cart-v1", FAV_KEY="kutadgu-favorites-v1", REC_KEY="kutadgu-recent-v1";
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const find=id=>C.find(x=>x.id===id);
function money(n){return n?`${Number(n).toLocaleString("tr-TR")} ₺":"باھا تېخى بېكىتىلمىگەن"}
function cart(){return get(CART_KEY,[])}
function updateBadge(){let n=cart().reduce((s,x)=>s+(x.qty||1),0);document.querySelectorAll(".cart-count").forEach(e=>e.textContent=n)}
function add(id,qty=1){let b=find(id);if(!b)return;let a=cart(),x=a.find(i=>i.id===id);if(x)x.qty+=qty;else a.push({id,qty});set(CART_KEY,a);updateBadge();toast("كىتاب سېۋەتكە قوشۇلدى 🛒")}
function remove(id){set(CART_KEY,cart().filter(x=>x.id!==id));updateBadge()}
function favs(){return get(FAV_KEY,[])}
function toggleFav(id){let a=favs();if(a.includes(id)){a=a.filter(x=>x!==id);toast("ياقتۇرۇلغانلاردىن چىقىرىلدى")}else{a.push(id);toast("ياقتۇرۇلغانلارغا قوشۇلدى ❤️")}set(FAV_KEY,a);renderFavButtons();}
function recent(id){let a=get(REC_KEY,[]).filter(x=>x!==id);a.unshift(id);set(REC_KEY,a.slice(0,12))}
function toast(msg){let t=document.querySelector(".shop-toast");if(!t){t=document.createElement("div");t.className="shop-toast";t.style.cssText="position:fixed;right:18px;bottom:18px;z-index:10000;background:#4b3327;color:#fff;padding:12px 18px;border-radius:9px;box-shadow:0 8px 25px rgba(0,0,0,.2);font-family:inherit";document.body.appendChild(t)}t.textContent=msg;t.style.opacity="1";clearTimeout(t._tm);t._tm=setTimeout(()=>t.style.opacity="0",1800)}
function injectFloat(){if(document.querySelector(".shop-floating"))return;let d=document.createElement("div");d.className="shop-floating";d.innerHTML=`<button class="shop-float-btn" onclick="location.href='cart.html'">🛒 سېۋەت <span class="cart-count">0</span></button><button class="shop-float-btn" onclick="location.href='favorites.html'">❤️ ياقتۇرغانلىرىم</button>`;document.body.appendChild(d);updateBadge()}
function cardId(card){let a=card.querySelector("a.book-image,a.book-cover,.detail-button,.book-button"),href=a&&a.getAttribute("href");let b=C.find(x=>x.href===href);if(b)return b.id;let title=card.querySelector(".book-title")?.textContent.trim();b=C.find(x=>x.title===title);return b?.id}
function decorateCards(){document.querySelectorAll(".book-card").forEach(card=>{let id=cardId(card);if(!id||card.querySelector(".book-actions"))return;let wrap=document.createElement("div");wrap.className="book-actions";wrap.innerHTML=`<button class="add-to-cart" data-cart-id="${id}">🛒 سېۋەتكە سېلىش</button><button class="favorite-button" data-fav-id="${id}">♡</button>`;let info=card.querySelector(".book-info");(info||card).appendChild(wrap)});document.querySelectorAll("[data-cart-id]").forEach(b=>b.onclick=()=>add(b.dataset.cartId));document.querySelectorAll("[data-fav-id]").forEach(b=>b.onclick=()=>toggleFav(b.dataset.favId));renderFavButtons()}
function renderFavButtons(){let a=favs();document.querySelectorAll("[data-fav-id]").forEach(b=>{let yes=a.includes(b.dataset.favId);b.classList.toggle("is-favorite",yes);b.textContent=yes?"♥":"♡"})}
function decorateDetail(){let id=document.body.dataset.bookId;if(!id)return;recent(id);let b=find(id);if(!b)return;let box=document.querySelector(".book-detail-info");if(box&&!box.querySelector(".detail-actions")){let d=document.createElement("div");d.className="detail-actions";d.innerHTML=`<div class="detail-price">${money(b.price)}</div><button class="add-to-cart detail-cart">🛒 سېۋەتكە سېلىش</button><button class="favorite-button" data-fav-id="${id}">♡ ياقتۇرۇش</button><button class="share-button">🔗 ھەمبەھىرلەش</button>`;box.appendChild(d)}let c=document.querySelector(".detail-cart");if(c)c.onclick=()=>add(id);let f=document.querySelector("[data-fav-id]");if(f)f.onclick=()=>toggleFav(id);let sh=document.querySelector(".share-button");if(sh)sh.onclick=()=>shareBook(b);renderFavButtons()}
async function shareBook(b){let url=location.href;try{if(navigator.share)await navigator.share({title:b.title,text:`${b.title} — ${b.author}`,url});else{await navigator.clipboard.writeText(url);toast("ئۇلىنىش كۆچۈرۈلدى 🔗")}}catch(e){}}
function miniCard(b){return `<article class="shop-mini-card"><button class="mini-heart" data-fav-id="${b.id}">♡</button><a href="${b.href}"><img src="${b.image||''}" alt="${b.title}" loading="lazy" onerror="this.style.visibility='hidden'"><div class="shop-mini-title">${b.title}</div><div class="shop-mini-meta">${b.author}</div><div class="shop-mini-price">${money(b.price)}</div></a><button class="add-to-cart" data-cart-id="${b.id}" style="margin-top:8px">🛒 سېۋەتكە سېلىش</button></article>`}
function renderHomeSections(){let host=document.querySelector("#homeShopSections");if(!host)return;let rec=get(REC_KEY,[]).map(find).filter(Boolean).slice(0,6);let fav=favs().map(find).filter(Boolean).slice(0,6);let newest=C.slice(0,8);let sections=[];sections.push(["🆕 يېڭى قوشۇلغان كىتابلار",newest]);if(rec.length)sections.push(["🕘 يېقىندا كۆرۈلگەن كىتابلار",rec]);if(fav.length)sections.push(["❤️ ياقتۇرغان كىتابلار",fav]);sections.push(["⭐ تەۋسىيە قىلىنغان كىتابلار",C.slice(0,6)]);host.innerHTML=sections.map(([t,arr])=>`<section class="shop-section"><h2>${t}</h2><div class="shop-grid">${arr.map(miniCard).join("")}</div></section>`).join("");host.querySelectorAll("[data-cart-id]").forEach(b=>b.onclick=()=>add(b.dataset.cartId));host.querySelectorAll("[data-fav-id]").forEach(b=>b.onclick=()=>toggleFav(b.dataset.favId));renderFavButtons()}
function searchEnhance(){let input=document.querySelector("#searchInput"),res=document.querySelector("#searchResults");if(!input||!res)return;let btn=document.querySelector("#searchButton");if(btn)btn.onclick=run;input.addEventListener("input",()=>{if(!input.value.trim())res.innerHTML="";else run()});function run(){let q=input.value.trim().toLocaleLowerCase("ug"),matches=C.filter(b=>[b.title,b.author,b.category].join(" ").toLocaleLowerCase("ug").includes(q));let sort=document.querySelector("#searchSort")?.value||"new";if(sort==="priceLow")matches.sort((a,b)=>(a.price||999999)-(b.price||999999));if(sort==="priceHigh")matches.sort((a,b)=>(b.price||0)-(a.price||0));if(sort==="title")matches.sort((a,b)=>a.title.localeCompare(b.title,"ug"));res.innerHTML=matches.length?`<div class="search-tools"><span>${matches.length} نەتىجە</span><select id="searchSort"><option value="new">تەرتىپى</option><option value="title">ئىسىم بويىچە</option><option value="priceLow">ئەرزانىدىن</option><option value="priceHigh">قىممىتىدىن</option></select></div>`+matches.map(b=>`<a class="search-result" href="${b.href}"><img class="search-result-image" src="${b.image}" alt="${b.title}" onerror="this.style.display='none'"><div class="search-result-content"><div class="search-result-title">${b.title}</div><div class="search-result-author">ئاپتورى: ${b.author}</div><div class="search-result-category">${b.category}</div><div class="search-result-category">${money(b.price)}</div></div></a>`).join(""):"<div class='search-empty'>بۇ ئىزدەش بويىچە كىتاب تېپىلمىدى.</div>";let s=document.querySelector("#searchSort");if(s)s.onchange=run}}
function cartPage(){let host=document.querySelector("#cartItems");if(!host)return;let items=cart().map(x=>({...x,b:find(x.id)})).filter(x=>x.b);let total=items.reduce((s,x)=>s+(x.b.price||0)*x.qty,0);host.innerHTML=items.length?items.map(x=>`<div class="cart-item"><img src="${x.b.image}" alt="${x.b.title}" onerror="this.style.visibility='hidden'"><div><div class="cart-title">${x.b.title}</div><div class="cart-meta">${x.b.author} · ${x.b.category}</div></div><div class="qty-control"><button data-minus="${x.b.id}">−</button><span>${x.qty}</span><button data-plus="${x.b.id}">+</button></div><div class="cart-line-price">${money((x.b.price||0)*x.qty)}</div><button class="remove-cart" data-remove="${x.b.id}">ئۆچۈرۈش</button></div>`).join("")+`<div class="cart-summary"><div class="cart-total">جەمئىي: ${money(total)}</div><button class="add-to-cart" id="copyOrder">📋 زاكاز ئۇچۇرىنى كۆچۈرۈش</button></div>`:`<div class="empty-state">🛒 سېۋەت ھازىرچە بوش.<br><a href="index.html#books">كىتاب كۆرۈش →</a></div>`;host.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));host.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));host.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>remove(b.dataset.remove)||cartPage());let order=document.querySelector("#copyOrder");if(order)order.onclick=copyOrder}
function changeQty(id,d){let a=cart(),x=a.find(i=>i.id===id);if(!x)return;x.qty=Math.max(1,x.qty+d);set(CART_KEY,a);cartPage();updateBadge()}
async function copyOrder(){let items=cart().map(x=>({...x,b:find(x.id)})).filter(x=>x.b);let lines=["قۇتادغۇبىلىك كىتابخانىسى — سېۋەت زاكازى",""];items.forEach(x=>lines.push(`${x.b.title} × ${x.qty} — ${money((x.b.price||0)*x.qty)}`));let total=items.reduce((s,x)=>s+(x.b.price||0)*x.qty,0);lines.push("",`جەمئىي: ${money(total)}`);try{await navigator.clipboard.writeText(lines.join("\n"));toast("زاكاز ئۇچۇرى كۆچۈرۈلدى 📋")}catch(e){alert(lines.join("\n"))}}
function init(){injectFloat();decorateCards();decorateDetail();searchEnhance();renderHomeSections();cartPage()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
window.kutadguShop={add,remove,toggleFav,cart};
})();
