-- قۇتادغۇبىلىك — Stage 8 store analytics dashboard RPC
-- Supabase > SQL Editor دا Run قىلىڭ. ئاگېنت / كود ئىجرا قىلمايدۇ.
-- Repeat-safe: ADD COLUMN IF NOT EXISTS / CREATE INDEX IF NOT EXISTS / CREATE OR REPLACE.
-- INSERT/UPDATE/DELETE يوق. analytics_events قۇرلىرى ئۆچۈرۈلمەيدۇ.
-- كىتاب سېتىش سانىغا تەگمەيدۇ. service_role ئاچىلمايدۇ.
--
-- بۇنى STAGE4_ANALYTICS_RPC_FIX.sql ۋە STAGE46_ANALYTICS_LEGACY_ID.sql
-- دىن كېيىن Run قىلىڭ (ئۇلار يوق بولسا مۇشۇ ھۆججەت جەدۋەلنىمۇ IF NOT EXISTS بىلەن تەييارلايدۇ).
--
-- نېمە قوشىدۇ:
--   legacy_id, meta ستونلىرى (كىتاب كىملىكى + WhatsApp سېۋەت ID لىرى)
--   get_kutadgu_analytics: funnel، top cart/WhatsApp كىتابلىرى، top searches
--   Admin-only EXECUTE. anon INSERT سىياسىتى ئۆزگەرمەيدۇ.

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  book_id text,
  search_query text,
  category text,
  result_count integer,
  item_count integer,
  order_total numeric(12,2),
  path text,
  session_id text,
  created_at timestamptz not null default now()
);

alter table public.analytics_events add column if not exists legacy_id text;
alter table public.analytics_events add column if not exists meta jsonb;

create index if not exists analytics_events_created_idx
  on public.analytics_events(created_at desc);
create index if not exists analytics_events_name_created_idx
  on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_book_created_idx
  on public.analytics_events(book_id, created_at desc)
  where book_id is not null;
create index if not exists analytics_events_search_created_idx
  on public.analytics_events(search_query, created_at desc)
  where search_query is not null;
create index if not exists analytics_events_name_book_created_idx
  on public.analytics_events(event_name, book_id, created_at desc)
  where book_id is not null;

alter table public.analytics_events enable row level security;

create or replace function public.get_kutadgu_analytics(p_days integer default 30)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days, 30), 365));
  v_since timestamptz := now() - make_interval(days => v_days);
  v_book_views bigint := 0;
  v_cart_adds bigint := 0;
  v_whatsapp bigint := 0;
  v_search_zeros bigint := 0;
  v_zero_events bigint := 0;
  v_page_views bigint := 0;
  v_zero_total bigint := 0;
  v_result jsonb;
begin
  if not public.is_kutadgu_admin() then
    raise exception 'admin only';
  end if;

  select
    count(*) filter (where event_name = 'page_view'),
    count(*) filter (where event_name = 'book_view'),
    count(*) filter (where event_name = 'add_to_cart'),
    count(*) filter (where event_name = 'whatsapp_order_click'),
    count(*) filter (where event_name = 'search' and coalesce(result_count, 0) = 0),
    count(*) filter (where event_name = 'zero_result_search')
  into v_page_views, v_book_views, v_cart_adds, v_whatsapp, v_search_zeros, v_zero_events
  from public.analytics_events
  where created_at >= v_since;

  v_zero_total := case when v_search_zeros > 0 then v_search_zeros else v_zero_events end;

  select jsonb_build_object(
    'page_views', v_page_views,
    'book_views', v_book_views,
    'cart_adds', v_cart_adds,
    'whatsapp_clicks', v_whatsapp,
    'zero_result_searches', v_zero_total,
    'funnel', jsonb_build_object(
      'views', v_book_views,
      'cart_adds', v_cart_adds,
      'whatsapp_clicks', v_whatsapp,
      'view_to_cart_pct', case when v_book_views > 0 then round((v_cart_adds::numeric * 100) / v_book_views, 1) else null end,
      'cart_to_whatsapp_pct', case when v_cart_adds > 0 then round((v_whatsapp::numeric * 100) / v_cart_adds, 1) else null end,
      'view_to_whatsapp_pct', case when v_book_views > 0 then round((v_whatsapp::numeric * 100) / v_book_views, 1) else null end
    ),
    'top_books', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.views desc)
      from (
        select coalesce(b.id::text, e.book_id) as book_id,
               coalesce(b.title, e.book_id) as title,
               count(*)::integer as views
        from public.analytics_events e
        left join public.books b
          on b.id::text = e.book_id
          or (
            b.legacy_id is not null
            and b.legacy_id <> ''
            and (b.legacy_id = e.book_id or b.legacy_id = e.legacy_id)
          )
        where e.created_at >= v_since
          and e.event_name = 'book_view'
          and e.book_id is not null
          and e.book_id <> ''
        group by coalesce(b.id::text, e.book_id), coalesce(b.title, e.book_id)
        order by count(*) desc
        limit 10
      ) t
    ), '[]'::jsonb),
    'top_cart_books', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.adds desc)
      from (
        select coalesce(b.id::text, e.book_id) as book_id,
               coalesce(b.title, e.book_id) as title,
               count(*)::integer as adds
        from public.analytics_events e
        left join public.books b
          on b.id::text = e.book_id
          or (
            b.legacy_id is not null
            and b.legacy_id <> ''
            and (b.legacy_id = e.book_id or b.legacy_id = e.legacy_id)
          )
        where e.created_at >= v_since
          and e.event_name = 'add_to_cart'
          and e.book_id is not null
          and e.book_id <> ''
        group by coalesce(b.id::text, e.book_id), coalesce(b.title, e.book_id)
        order by count(*) desc
        limit 10
      ) t
    ), '[]'::jsonb),
    'top_whatsapp_books', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.clicks desc)
      from (
        select coalesce(b.id::text, x.book_id) as book_id,
               coalesce(b.title, x.book_id) as title,
               count(*)::integer as clicks
        from (
          select coalesce(ids.book_id, e.book_id) as book_id
          from public.analytics_events e
          left join lateral (
            select jsonb_array_elements_text(e.meta->'book_ids') as book_id
            where e.meta is not null
              and jsonb_typeof(e.meta->'book_ids') = 'array'
          ) ids on true
          where e.created_at >= v_since
            and e.event_name = 'whatsapp_order_click'
        ) x
        left join public.books b
          on b.id::text = x.book_id
          or (
            b.legacy_id is not null
            and b.legacy_id <> ''
            and b.legacy_id = x.book_id
          )
        where x.book_id is not null and x.book_id <> ''
        group by coalesce(b.id::text, x.book_id), coalesce(b.title, x.book_id)
        order by count(*) desc
        limit 10
      ) t
    ), '[]'::jsonb),
    'top_searches', coalesce((
      select jsonb_agg(to_jsonb(s) order by s.searches desc)
      from (
        select search_query as query,
               count(*)::integer as searches
        from public.analytics_events
        where created_at >= v_since
          and event_name = 'search'
          and search_query is not null
          and search_query <> ''
        group by search_query
        order by count(*) desc
        limit 10
      ) s
    ), '[]'::jsonb),
    'zero_searches', coalesce((
      select jsonb_agg(to_jsonb(z) order by z.searches desc)
      from (
        select search_query as query,
               count(*)::integer as searches
        from public.analytics_events
        where created_at >= v_since
          and search_query is not null
          and search_query <> ''
          and (
            (v_search_zeros > 0 and event_name = 'search' and coalesce(result_count, 0) = 0)
            or
            (v_search_zeros = 0 and event_name = 'zero_result_search')
          )
        group by search_query
        order by count(*) desc
        limit 10
      ) z
    ), '[]'::jsonb)
  ) into v_result;

  return coalesce(v_result, jsonb_build_object(
    'page_views', 0,
    'book_views', 0,
    'cart_adds', 0,
    'whatsapp_clicks', 0,
    'zero_result_searches', 0,
    'funnel', jsonb_build_object(
      'views', 0,
      'cart_adds', 0,
      'whatsapp_clicks', 0,
      'view_to_cart_pct', null,
      'cart_to_whatsapp_pct', null,
      'view_to_whatsapp_pct', null
    ),
    'top_books', '[]'::jsonb,
    'top_cart_books', '[]'::jsonb,
    'top_whatsapp_books', '[]'::jsonb,
    'top_searches', '[]'::jsonb,
    'zero_searches', '[]'::jsonb
  ));
end;
$$;

revoke all on function public.get_kutadgu_analytics(integer) from public;
revoke all on function public.get_kutadgu_analytics(integer) from anon;
grant execute on function public.get_kutadgu_analytics(integer) to authenticated;

commit;
