-- قۇتادغۇبىلىك — Stage 4 Analytics RPC
-- Supabase > SQL Editor دا بىر قېتىم Run قىلىڭ. بۇ ھۆججەتنى كود ئىجرا قىلمايدۇ.
-- Repeat-safe: CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS / CREATE OR REPLACE.
-- INSERT/UPDATE/DELETE يوق. كىتاب قۇرلىرى ئۆزگەرمەيدۇ. service_role ئاچىلمايدۇ.
--
-- نېمە ئۈچۈن: live project تا public.analytics_events ۋە
-- public.get_kutadgu_analytics(p_days integer) يوق (PostgREST PGRST202).
-- Admin .rpc("get_kutadgu_analytics",{p_days}) توغرا؛ Database تەرەپ يېتىشمىگەن.
--
-- كىم ئىجرا قىلالايدۇ: پەقەت authenticated + is_kutadgu_admin().
-- anon EXECUTE يوق. ئېلخەت/پارول/auth metadata قايتمايدۇ.

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  book_id text,
  search_query text,
  category text,
  result_count integer,
  item_count integer,
  order_total numeric(12,2),
  path text,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_idx
  on public.analytics_events(created_at desc);
create index if not exists analytics_events_name_created_idx
  on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_book_created_idx
  on public.analytics_events(book_id, created_at desc)
  where book_id is not null;
create index if not exists analytics_events_search_created_idx
  on public.analytics_events(search_query, created_at desc)
  where search_query is not null;

alter table public.analytics_events add column if not exists legacy_id text;
alter table public.analytics_events add column if not exists meta jsonb;

alter table public.analytics_events enable row level security;

grant insert on public.analytics_events to anon, authenticated;
grant select on public.analytics_events to authenticated;

drop policy if exists "public can insert analytics" on public.analytics_events;
create policy "public can insert analytics"
  on public.analytics_events
  for insert
  to anon, authenticated
  with check (
    event_name in (
      'page_view',
      'book_view',
      'add_to_cart',
      'whatsapp_order_click',
      'search',
      'zero_result_search',
      'add_to_favorite',
      'remove_from_favorite',
      'contact_click',
      'filter_apply'
    )
    and (book_id is null or char_length(book_id) <= 32)
    and (search_query is null or char_length(search_query) <= 80)
    and (category is null or char_length(category) <= 100)
    and (path is null or char_length(path) <= 180)
    and (session_id is null or char_length(session_id) <= 100)
    and (legacy_id is null or char_length(legacy_id) <= 120)
    and (result_count is null or (result_count >= 0 and result_count <= 100000))
    and (item_count is null or (item_count >= 0 and item_count <= 200))
    and (order_total is null or (order_total >= 0 and order_total <= 9999999.99))
    and case
      when meta is null then true
      when event_name is distinct from 'whatsapp_order_click' then false
      when jsonb_typeof(meta) is distinct from 'object' then false
      when not (meta ? 'book_ids') then false
      when (meta - 'book_ids') is distinct from '{}'::jsonb then false
      when jsonb_typeof(meta -> 'book_ids') is distinct from 'array' then false
      when coalesce(jsonb_array_length(meta -> 'book_ids'), 0) > 200 then false
      else not exists (
        select 1
        from jsonb_array_elements(meta -> 'book_ids') as elem(value)
        where jsonb_typeof(elem.value) is distinct from 'string'
           or char_length(elem.value #>> '{}') > 32
           or (elem.value #>> '{}') !~ '^\d+$'
      )
    end
    and created_at >= (now() - interval '5 minutes')
    and created_at <= (now() + interval '5 minutes')
  );

drop policy if exists "admin can read analytics" on public.analytics_events;
create policy "admin can read analytics"
  on public.analytics_events
  for select
  to authenticated
  using (public.is_kutadgu_admin());

do $$
declare
  seq text;
begin
  seq := pg_get_serial_sequence('public.analytics_events', 'id');
  if seq is not null then
    execute format('grant usage, select on sequence %s to anon, authenticated', seq);
  end if;
end $$;

create or replace function public.get_kutadgu_analytics(p_days integer default 30)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days, 30), 365));
  v_since timestamptz := now() - make_interval(days => v_days);
  v_result jsonb;
begin
  if not public.is_kutadgu_admin() then
    raise exception 'admin only';
  end if;

  select jsonb_build_object(
    'page_views', (
      select count(*)::bigint
      from public.analytics_events
      where created_at >= v_since and event_name = 'page_view'
    ),
    'book_views', (
      select count(*)::bigint
      from public.analytics_events
      where created_at >= v_since and event_name = 'book_view'
    ),
    'cart_adds', (
      select count(*)::bigint
      from public.analytics_events
      where created_at >= v_since and event_name = 'add_to_cart'
    ),
    'whatsapp_clicks', (
      select count(*)::bigint
      from public.analytics_events
      where created_at >= v_since and event_name = 'whatsapp_order_click'
    ),
    'top_books', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.views desc)
      from (
        select e.book_id,
               coalesce(b.title, e.book_id) as title,
               count(*)::integer as views
        from public.analytics_events e
        left join public.books b on b.id::text = e.book_id
        where e.created_at >= v_since
          and e.event_name = 'book_view'
          and e.book_id is not null
          and e.book_id <> ''
        group by e.book_id, b.title
        order by count(*) desc
        limit 10
      ) t
    ), '[]'::jsonb),
    'zero_searches', coalesce((
      select jsonb_agg(to_jsonb(z) order by z.searches desc)
      from (
        select search_query as query,
               count(*)::integer as searches
        from public.analytics_events
        where created_at >= v_since
          and event_name = 'search'
          and coalesce(result_count, 0) = 0
          and search_query is not null
          and search_query <> ''
        group by search_query
        order by count(*) desc
        limit 10
      ) z
    ), '[]'::jsonb)
  ) into v_result;

  return coalesce(v_result, jsonb_build_object(
    'page_views', 0,
    'book_views', 0,
    'cart_adds', 0,
    'whatsapp_clicks', 0,
    'top_books', '[]'::jsonb,
    'zero_searches', '[]'::jsonb
  ));
end;
$$;

revoke all on function public.get_kutadgu_analytics(integer) from public;
revoke all on function public.get_kutadgu_analytics(integer) from anon;
grant execute on function public.get_kutadgu_analytics(integer) to authenticated;

commit;
