-- ============================================================================
-- Kutadgu Bilig — Stage 65 price history + safe rollback
-- MANUAL / REVIEWED APPLY ONLY. Do not run from CI or the browser.
-- Repeat-safe. Does NOT rewrite book rows, backfill prices, or invent history.
-- Does not change books SELECT policies, original_price, or is_kutadgu_admin().
-- ============================================================================
--
-- Purpose:
--   Record every committed change to public.books.price in
--   public.book_price_history via an AFTER UPDATE OF price trigger.
--   Allow AAL2 Admins to roll CURRENT selling price back to a previous
--   historical old_price through public.rollback_book_price().
--
-- After apply:
--   books.price and books.original_price are unchanged.
--   book_price_history has 0 rows (no backfill).
--   History INSERT is trigger-only (SECURITY DEFINER). Browser has SELECT
--   for Admin+AAL2 and no INSERT/UPDATE/DELETE on history.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.book_price_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id text NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
  old_price numeric(12,2),
  new_price numeric(12,2),
  changed_by uuid,
  change_kind text NOT NULL DEFAULT 'price_change',
  changed_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.book_price_history IS
  'Append-only selling-price history. Written only by log_book_price_change(). Never backfilled.';

ALTER TABLE public.book_price_history DROP CONSTRAINT IF EXISTS book_price_history_change_kind_chk;
ALTER TABLE public.book_price_history
  ADD CONSTRAINT book_price_history_change_kind_chk
  CHECK (change_kind IN ('price_change', 'rollback'));

CREATE INDEX IF NOT EXISTS book_price_history_book_changed_idx
  ON public.book_price_history (book_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS book_price_history_changed_idx
  ON public.book_price_history (changed_at DESC);

ALTER TABLE public.book_price_history ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.book_price_history FROM PUBLIC;
REVOKE ALL ON TABLE public.book_price_history FROM anon;
REVOKE ALL ON TABLE public.book_price_history FROM authenticated;
GRANT SELECT ON TABLE public.book_price_history TO authenticated;

DROP POLICY IF EXISTS "admin aal2 can read price history" ON public.book_price_history;
CREATE POLICY "admin aal2 can read price history"
  ON public.book_price_history
  FOR SELECT
  TO authenticated
  USING (
    public.is_kutadgu_admin()
    AND (select auth.jwt()->>'aal') = 'aal2'
  );

CREATE OR REPLACE FUNCTION public.log_book_price_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_kind text;
BEGIN
  IF OLD.price IS NOT DISTINCT FROM NEW.price THEN
    RETURN NEW;
  END IF;
  v_kind := nullif(current_setting('kutadgu.price_change_kind', true), '');
  IF v_kind IS NULL OR v_kind NOT IN ('price_change', 'rollback') THEN
    v_kind := 'price_change';
  END IF;
  INSERT INTO public.book_price_history (
    book_id, old_price, new_price, changed_by, change_kind
  ) VALUES (
    NEW.id, OLD.price, NEW.price, auth.uid(), v_kind
  );
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.log_book_price_change() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.log_book_price_change() FROM anon;
REVOKE ALL ON FUNCTION public.log_book_price_change() FROM authenticated;

DROP TRIGGER IF EXISTS books_log_price_change ON public.books;
CREATE TRIGGER books_log_price_change
  AFTER UPDATE OF price ON public.books
  FOR EACH ROW
  WHEN (OLD.price IS DISTINCT FROM NEW.price)
  EXECUTE FUNCTION public.log_book_price_change();

CREATE OR REPLACE FUNCTION public.rollback_book_price(
  p_book_id text,
  p_history_id bigint,
  p_expected_price numeric
)
RETURNS TABLE(id text, price numeric, original_price numeric)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_book public.books%ROWTYPE;
  v_hist public.book_price_history%ROWTYPE;
  v_target numeric(12,2);
BEGIN
  IF NOT public.is_kutadgu_admin() THEN
    RAISE EXCEPTION 'Admin permission required';
  END IF;
  IF (select auth.jwt()->>'aal') IS DISTINCT FROM 'aal2' THEN
    RAISE EXCEPTION 'AAL2 required' USING ERRCODE = '42501';
  END IF;
  IF p_book_id IS NULL OR btrim(p_book_id) = '' THEN
    RAISE EXCEPTION 'كىتاب ID تېپىلمىدى.';
  END IF;
  IF p_history_id IS NULL THEN
    RAISE EXCEPTION 'تارىخ قۇرى تېپىلمىدى.';
  END IF;

  SELECT * INTO v_book
  FROM public.books
  WHERE public.books.id = p_book_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'كىتاب تېپىلمىدى.';
  END IF;

  SELECT * INTO v_hist
  FROM public.book_price_history
  WHERE public.book_price_history.id = p_history_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'تارىخ قۇرى تېپىلمىدى.';
  END IF;
  IF v_hist.book_id IS DISTINCT FROM v_book.id THEN
    RAISE EXCEPTION 'تارىخ قۇرى بۇ كىتابقا تەۋە ئەمەس.';
  END IF;

  v_target := v_hist.old_price;
  IF v_target IS NULL OR v_target < 0 THEN
    RAISE EXCEPTION 'قايتۇرۇلىدىغان باھا ئىناۋەتسىز.';
  END IF;

  IF v_book.price IS DISTINCT FROM p_expected_price THEN
    RAISE EXCEPTION 'باھا باشقا بەتتە ئۆزگەرتىلگەن. كىتابنى قايتا ئېچىپ قايتا سىناڭ.';
  END IF;

  IF v_book.price IS NOT DISTINCT FROM v_target THEN
    RETURN QUERY
      SELECT v_book.id AS id, v_book.price AS price, v_book.original_price AS original_price;
    RETURN;
  END IF;

  PERFORM set_config('kutadgu.price_change_kind', 'rollback', true);

  UPDATE public.books
  SET price = v_target
  WHERE public.books.id = v_book.id
    AND public.books.price IS NOT DISTINCT FROM v_book.price;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'باھا باشقا بەتتە ئۆزگەرتىلگەن. كىتابنى قايتا ئېچىپ قايتا سىناڭ.';
  END IF;

  RETURN QUERY
    SELECT b.id AS id, b.price AS price, b.original_price AS original_price
    FROM public.books b
    WHERE b.id = v_book.id;
END;
$$;

REVOKE ALL ON FUNCTION public.rollback_book_price(text, bigint, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.rollback_book_price(text, bigint, numeric) FROM anon;
GRANT EXECUTE ON FUNCTION public.rollback_book_price(text, bigint, numeric) TO authenticated;

COMMIT;

-- ============================================================================
-- Read-only verification (run separately AFTER apply). Does NOT modify data.
-- Expected book_price_history count immediately after migration: 0
-- ============================================================================
--
-- 1) table columns/types
-- SELECT column_name, data_type, udt_name, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'book_price_history'
-- ORDER BY ordinal_position;
--
-- 2) indexes
-- SELECT indexname, indexdef
-- FROM pg_indexes
-- WHERE schemaname = 'public' AND tablename = 'book_price_history'
-- ORDER BY indexname;
--
-- 3) trigger exists/enabled
-- SELECT tgname, tgenabled, pg_get_triggerdef(oid)
-- FROM pg_trigger
-- WHERE tgrelid = 'public.books'::regclass
--   AND NOT tgisinternal
--   AND tgname = 'books_log_price_change';
--
-- 4) RLS enabled
-- SELECT relname, relrowsecurity, relforcerowsecurity
-- FROM pg_class
-- WHERE oid = 'public.book_price_history'::regclass;
--
-- 5) policies
-- SELECT polname, polcmd, polroles::regrole[], pg_get_expr(polqual, polrelid)
-- FROM pg_policy
-- WHERE polrelid = 'public.book_price_history'::regclass;
--
-- 6) grants/privileges
-- SELECT grantee, privilege_type
-- FROM information_schema.role_table_grants
-- WHERE table_schema = 'public' AND table_name = 'book_price_history'
-- ORDER BY grantee, privilege_type;
--
-- 7) rollback function
-- SELECT p.proname, pg_get_function_identity_arguments(p.oid), p.prosecdef
-- FROM pg_proc p
-- JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public' AND p.proname = 'rollback_book_price';
--
-- 8) trigger function
-- SELECT p.proname, pg_get_function_identity_arguments(p.oid), p.prosecdef
-- FROM pg_proc p
-- JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public' AND p.proname = 'log_book_price_change';
--
-- 9) existing history count (must be 0; no backfill)
-- SELECT count(*) AS history_rows FROM public.book_price_history;
