-- Throwaway legacy schema for STAGE100. Not production.
-- Columns match analytics_events before visitor_id, event_id, host,
-- occurred_at, and action_seq. Roles are NOLOGIN.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS auth;

CREATE OR REPLACE FUNCTION auth.jwt()
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  SELECT jsonb_build_object('aal', nullif(current_setting('test.aal', true), ''));
$$;

CREATE OR REPLACE FUNCTION public.is_kutadgu_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT current_setting('test.admin', true) = 'on';
$$;

GRANT USAGE ON SCHEMA auth TO anon, authenticated;
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON FUNCTION auth.jwt() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_kutadgu_admin() TO anon, authenticated;

CREATE TABLE public.books (
  id bigint PRIMARY KEY,
  title text,
  legacy_id text
);

INSERT INTO public.books (id, title, legacy_id) VALUES
  (2, 'Low', 'shared-slug'),
  (9, 'High', 'shared-slug'),
  (15, 'Canon', 'other');

CREATE TABLE public.analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name text NOT NULL,
  book_id text,
  search_query text,
  category text,
  result_count integer,
  item_count integer,
  order_total numeric(12,2),
  path text,
  session_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  legacy_id text,
  meta jsonb
);

CREATE INDEX analytics_events_created_idx
  ON public.analytics_events (created_at DESC);
CREATE INDEX analytics_events_name_created_idx
  ON public.analytics_events (event_name, created_at DESC);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

GRANT INSERT ON public.analytics_events TO anon, authenticated;
GRANT SELECT ON public.analytics_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.analytics_events_id_seq TO anon, authenticated;

CREATE POLICY "admin can read analytics"
  ON public.analytics_events
  FOR SELECT
  TO authenticated
  USING (
    public.is_kutadgu_admin()
    AND (SELECT auth.jwt()->>'aal') = 'aal2'
  );
