-- Throwaway legacy analytics schema for Stage 114. Not production.
-- Matches analytics_events before visitor_id and event_id.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS auth;

CREATE OR REPLACE FUNCTION auth.jwt()
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  SELECT jsonb_build_object('aal', nullif(current_setting('test.aal', true), ''));
$$;

CREATE OR REPLACE FUNCTION public.is_kutadgu_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT current_setting('test.admin', true) = 'on';
$$;

GRANT USAGE ON SCHEMA auth TO anon, authenticated;
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON FUNCTION auth.jwt() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_kutadgu_admin() TO anon, authenticated;

CREATE TABLE public.books (
  id bigint PRIMARY KEY,
  title text
);

INSERT INTO public.books (id, title) VALUES (15, 'Canon');

CREATE TABLE public.analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name text NOT NULL,
  book_id text,
  search_query text,
  category text,
  result_count integer,
  item_count integer,
  order_total numeric(12,2),
  path text,
  session_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  legacy_id text,
  meta jsonb
);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

GRANT INSERT ON public.analytics_events TO anon, authenticated;
GRANT SELECT ON public.analytics_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.analytics_events_id_seq TO anon, authenticated;

CREATE POLICY "public can insert analytics"
  ON public.analytics_events
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    event_name in (
      'page_view', 'book_view', 'book_engagement_detail', 'book_engagement_cart',
      'add_to_cart', 'whatsapp_order_click', 'search', 'zero_result_search',
      'add_to_favorite', 'remove_from_favorite', 'contact_click', 'filter_apply'
    )
    and (book_id is null or char_length(book_id) <= 32)
    and (path is null or char_length(path) <= 180)
    and (session_id is null or char_length(session_id) <= 100)
    and created_at >= (now() - interval '5 minutes')
    and created_at <= (now() + interval '5 minutes')
  );

CREATE POLICY "admin can read analytics"
  ON public.analytics_events
  FOR SELECT
  TO authenticated
  USING (
    public.is_kutadgu_admin()
    AND (SELECT auth.jwt()->>'aal') = 'aal2'
  );

-- Historical public traffic. Inserted before the visit trigger exists.
INSERT INTO public.analytics_events (event_name, path, session_id, created_at) VALUES
  ('page_view', '/index.html', 'old-session', timestamptz '2026-08-01 10:00:00+03'),
  (
    'page_view',
    '/index.html',
    'yesterday-session',
    ((timezone('Europe/Istanbul', now()))::date - 1)::timestamp AT TIME ZONE 'Europe/Istanbul' + interval '12 hours'
  ),
  ('book_view', '/book/15', 'old-session', now() - interval '10 days'),
  ('book_view', '/book/15', 'old-session', now() - interval '40 days'),
  ('add_to_cart', '/book/15', 'old-session', now() - interval '10 days'),
  ('whatsapp_order_click', '/cart.html', 'old-session', now() - interval '10 days');
